# Generated by Django 4.2.28 on 2026-02-06 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Xodim ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Rasm')),
                ('face_label', models.IntegerField(unique=True, verbose_name='Face Label (LBPH)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Kirim'), ('OUT', 'Chiqim')], db_index=True, max_length=10, verbose_name='Turi')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('VERIFIED', 'Tasdiqlangan'), ('CANCELLED', 'Bekor qilingan')], db_index=True, default='PENDING', max_length=10, verbose_name='Holat')),
                ('face_verified', models.BooleanField(default=False, verbose_name='Face tasdiqlandi')),
                ('face_confidence', models.FloatField(blank=True, null=True, verbose_name='Face ishonch darajasi')),
                ('face_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Face tasdiqlash vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('face_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.employee', verbose_name='Face ID xodim')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to=settings.AUTH_USER_MODEL, verbose_name='Bajaruvchi')),
                ('reversed_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='inventory.movement', verbose_name='Bekor qilingan movement')),
            ],
            options={
                'verbose_name': 'Harakat',
                'verbose_name_plural': 'Harakatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Mahsulot nomi')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Shtrix kod (QR)')),
                ('unit', models.CharField(max_length=20, verbose_name="O'lchov birligi")),
                ('min_stock', models.IntegerField(default=0, verbose_name='Minimal zaxira')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Birlik narxi')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.movement', verbose_name='Harakat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_items', to='inventory.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Harakat elementi',
                'verbose_name_plural': 'Harakat elementlari',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock', serialize=False, to='inventory.product', verbose_name='Mahsulot')),
                ('current_qty', models.IntegerField(default=0, verbose_name='Joriy miqdor')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zaxira',
                'verbose_name_plural': 'Zaxiralar',
                'indexes': [models.Index(fields=['current_qty'], name='inventory_s_current_89f304_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='inventory_p_categor_607069_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='inventory_p_name_f6a6a1_idx'),
        ),
        migrations.AddIndex(
            model_name='movementitem',
            index=models.Index(fields=['product'], name='inventory_m_product_ea446b_idx'),
        ),
        migrations.AddIndex(
            model_name='movementitem',
            index=models.Index(fields=['movement'], name='inventory_m_movemen_f53488_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['performed_by'], name='inventory_m_perform_8a3496_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['face_employee'], name='inventory_m_face_em_080a36_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['movement_type'], name='inventory_m_movemen_6d66c7_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['status'], name='inventory_m_status_0e35b5_idx'),
        ),
    ]
