# Generated by Django 4.2.28 on 2026-02-11 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_commander',
            field=models.BooleanField(default=False, verbose_name='Komandir (Rahbar)'),
        ),
        migrations.AddField(
            model_name='movement',
            name='is_emergency',
            field=models.BooleanField(default=False, verbose_name='Ekstrenniy rejim'),
        ),
        migrations.CreateModel(
            name='EmployeeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='inventory.employee', verbose_name='Xodim')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employees', to='inventory.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Biriktirilgan mahsulot',
                'verbose_name_plural': 'Biriktirilgan mahsulotlar',
                'unique_together': {('employee', 'product')},
            },
        ),
    ]
