# Generated by Django 4.2.28 on 2026-02-11 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_employee_is_commander_movement_is_emergency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assigned_categories',
            field=models.ManyToManyField(blank=True, related_name='assigned_employees', to='inventory.category', verbose_name='Biriktirilgan toifalar'),
        ),
        migrations.AddField(
            model_name='movement',
            name='target_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegated_movements', to='inventory.employee', verbose_name='Maqsadli xodim'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='face_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.employee', verbose_name='Face ID xodim (aktor)'),
        ),
        migrations.DeleteModel(
            name='EmployeeProduct',
        ),
    ]
