# Generated by Django 4.2.28 on 2026-02-15 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_employee_assigned_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='inventory.employee', verbose_name='Rahbar (Komandir)'),
        ),
        migrations.AddField(
            model_name='product',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_products', to='inventory.employee', verbose_name='Biriktirilgan xodim'),
        ),
    ]
